CREATE DATABASE JUNCAO;
USE JUNCAO;

CREATE TABLE TABELA_A
(NOME VARCHAR(50));


CREATE TABLE TABELA_B
(NOME VARCHAR(50));


INSERT INTO TABELA_A VALUES ('Fernanda');
INSERT INTO TABELA_A VALUES ('Zoraide');
INSERT INTO TABELA_A VALUES ('Luiz');
INSERT INTO TABELA_A VALUES ('Fernando');

INSERT INTO TABELA_B VALUES ('Carlos');
INSERT INTO TABELA_B VALUES ('Evandro');
INSERT INTO TABELA_B VALUES ('Luiz');
INSERT INTO TABELA_B VALUES ('Fernando');


